name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  test:
    uses: TanklesXL/glint/.github/workflows/test.yml@main

  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          version="v$(cat gleam.toml | grep -m 1 "version" | sed -r "s/version *= *\"([[:digit:].]+)\"/\1/")"
          if [ "$version" != "${{ github.ref_name }}" ]; then
            echo "tag '${{ github.ref_name }}' does not match the version in gleam.toml"
            echo "expected a tag name 'v$version'"
            exit 1
          fi

  release-gh:
    runs-on: ubuntu-latest
    needs: [test, version]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v1

  release-hex:
    runs-on: ubuntu-latest
    needs: [test, version]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache/restore@v4
        with:
          path: ./build/packages
          key: deps-${{ hashFiles('manifest.toml') }}
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26
          rebar3-version: 3
          gleam-version: "1.1.0"
      - name: publish to hex
        env:
          HEXPM_USER: ${{ secrets.HEXPM_USER }}
          HEXPM_PASS: ${{ secrets.HEXPM_PASS }}
        run: gleam publish -y
